### ISSUE TITLE
Hprose(python)  RPC services with protobuf

### ISSUE THREAD

**Issue by xzhacker123** [hprose/hprose-python#2]
Hi！
你好！
At the moment I want to test some RPC services with protobuf+hprose(python) , but hprose client doesn't seem to support it.

`
        import hprose
	from pp import token_pb2
	client = hprose.HproseClient(r'http://xxxx.xxx.xxx.xxx/token')
        req = token_pb2.GetTokenRequest(MemberId=1)
	client.GetToken(req)`

`Traceback (most recent call last):
  File "E:/PycharmProject/hprose/hprose-python-master/examples/protos/client.py", line 31, in <module>
    get_token2()
  File "E:/PycharmProject/hprose/hprose-python-master/examples/protos/client.py", line 29, in get_token2
    client.GetToken(req)
  File "D:\Python\Python27\lib\site-packages\hprose\client.py", line 39, in __call__
    return self.__invoke(self.__name, list(args), callback, onerror, byref, resultMode, simple)
  File "D:\Python\Python27\lib\site-packages\hprose\client.py", line 87, in invoke
    return self.__invoke(name, args, byref, resultMode, simple)
  File "D:\Python\Python27\lib\site-packages\hprose\client.py", line 194, in __invoke
    data = self.__doOutput(name, args, byref, simple)
  File "D:\Python\Python27\lib\site-packages\hprose\client.py", line 141, in __doOutput
    writer.writeList(args)
  File "D:\Python\Python27\lib\site-packages\hprose\io.py", line 781, in writeList
    for i in xrange(count): self.serialize(l[i])
  File "D:\Python\Python27\lib\site-packages\hprose\io.py", line 658, in serialize
    elif isinstance(v, object): self.writeObjectWithRef(v)
  File "D:\Python\Python27\lib\site-packages\hprose\io.py", line 823, in writeObjectWithRef
    if not self.refer.write(obj): self.writeObject(obj)
  File "D:\Python\Python27\lib\site-packages\hprose\io.py", line 816, in writeObject
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute`

Is GetTokenRequest instance create by python2 whitout "__dict__"?
TKS!

**Comment by andot** [comment]
正常定义的对象，都应该可以使用 vars 来进行反射啊，你这个对象不支持反射，我也不知道该怎么处理。

**Comment by xzhacker123** [comment]
用protobuf生成的py就很奇怪ε=(´ο｀*)))唉
`message GetTokenRequest{
    int64   MemberId = 1;
}`

GetTokenRequest = _reflection.GeneratedProtocolMessageType('GetTokenRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETTOKENREQUEST,
  __module__ = 'token_pb2'
  ·# @@protoc_insertion_point(class_scope:protos.GetTokenRequest)
  ))
_sym_db.RegisterMessage(GetTokenRequest)

大佬指条明路呗！

**Comment by andot** [comment]
没用过 protobuf 不知道怎么存取它的对象，你知道吗？

**Comment by xzhacker123** [comment]
菜鸡一枚，正在学习中。。。
